# Generated by Django 5.0.2 on 2024-02-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    
    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studid', models.IntegerField()),
                ('studname', models.CharField(max_length=70)),
                ('studemail', models.EmailField(max_length=70)),
                ('studpass', models.CharField(max_length=70)),
            ],
        ),
    ]
